language: 'ruby'
dist: 'trusty'
sudo: false
cache: bundler

notifications:
  email: false
  slack:
    on_success: 'always'
    on_failure: 'always'
    rooms:
      secure: BvxKBW223g/HPLFg5TMcc0T6iU2RoseCtuentB7BYQ4ia6ufRPr+ywNB6pw0CR76I6eTtFx0uHgdQ6/xd0hJLI2nCB8F7yiJmNJUXO6HmS2AttRhpfmmKObfDCm5+7uDdwm2aReYriQyew3WZ8T47SLs1XWK7p+Yv/AsZwdaSHU=
  webhooks: https://www.travisbuddy.com/

before_script:
  - 'mysql -e "CREATE DATABASE IF NOT EXISTS fae_dummy_test CHARACTER SET utf8 COLLATE utf8_general_ci;"'
  - 'cd spec/dummy'
  - 'bundle exec rake db:schema:load --trace'
  - 'cd ../../'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'

env:
  global:
    - 'RAILS_ENV=test'

services:
  - 'mysql'

rvm:
  - '2.3'

gemfile:
  - 'gemfiles/rails_4_1.gemfile'
  - 'gemfiles/rails_4_2.gemfile'
  - 'gemfiles/rails_5_0.gemfile'
